# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b6f32053fa1f855128813fad84a211b9d3c11453180a328ef94ebf0b2c5e95aca531b6e25fd1c29082b67589b163654a46d7eb927b66528ec9d61f9a9bfb569

test:
  secret_key_base: 5ccfb5ac2464b5d130a7fb66841becaeb1c95a51b426086a551bf074f62a3f9a8b74acb77ab7bfe38ef05e597d28cf32cce5150eaca0da815428b21a7139e46a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
